language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools # intentional, see travis-ci/docs-travis-ci-com#779
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+
